name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: erlef/setup-beam@v1.16
        with:
          otp-version: '26.1'
          gleam-version: '0.32'
          rebar3-version: '3'
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
